// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using  Cliente.Migrations;

#nullable disable

namespace  Cliente.Migrations.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20241031203157_AddTabelas__01")]
    partial class AddTabelas__01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity(" Cliente.Domain.Entities.Banco", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoBanco")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("codigo_banco");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime?>("DataRegistro")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_registro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_banco");

                    b.ToTable("banco", (string)null);
                });

            modelBuilder.Entity(" Cliente.Domain.Entities.Cessionario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cnpj");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inativacao");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_registro");

                    b.Property<int>("IdAdministrador")
                        .HasColumnType("integer")
                        .HasColumnName("id_administrador");

                    b.Property<int?>("IdBancoCustodiante")
                        .HasColumnType("integer")
                        .HasColumnName("id_banco_custodiante");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_cessionario");

                    b.ToTable("cessionario", (string)null);
                });

            modelBuilder.Entity(" Cliente.Domain.Entities.ContaCorrente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Agencia")
                        .HasColumnType("integer")
                        .HasColumnName("agencia");

                    b.Property<int>("AgenciaDigito")
                        .HasColumnType("integer")
                        .HasColumnName("agencia_digito");

                    b.Property<int>("Conta")
                        .HasColumnType("integer")
                        .HasColumnName("conta");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inativacao");

                    b.Property<DateTime?>("DataRegistro")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_registro");

                    b.Property<int>("IdBanco")
                        .HasColumnType("integer")
                        .HasColumnName("id_banco");

                    b.HasKey("Id")
                        .HasName("pk_conta_corrente");

                    b.ToTable("conta_corrente", (string)null);
                });

            modelBuilder.Entity(" Cliente.Domain.Entities.Empresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cnpj");

                    b.Property<string>("CodigoKeycloak")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_keycloak");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inativacao");

                    b.Property<DateTime?>("DataRegistro")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_registro");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.HasKey("Id")
                        .HasName("pk_empresa");

                    b.ToTable("empresa", (string)null);
                });

            modelBuilder.Entity(" Cliente.Domain.Entities.Operacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ContaCobranca")
                        .HasColumnType("integer")
                        .HasColumnName("conta_cobranca");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inativacao");

                    b.Property<DateTime?>("DataRegistro")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_registro");

                    b.Property<string>("Detalhe")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasColumnName("detalhe");

                    b.Property<int>("IdCessionario")
                        .HasColumnType("integer")
                        .HasColumnName("id_cessionario");

                    b.Property<int>("IdModalidadeOperacao")
                        .HasColumnType("integer")
                        .HasColumnName("id_modalidade_operacao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.HasKey("Id")
                        .HasName("pk_operacoe");

                    b.ToTable("operacoe", (string)null);
                });

            modelBuilder.Entity(" Cliente.Domain.Entities.OperacaoCedente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Coobrigacao")
                        .HasColumnType("boolean")
                        .HasColumnName("coobrigacao");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime?>("DataRegistro")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_registro");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdOperacao")
                        .HasColumnType("integer")
                        .HasColumnName("id_operacao");

                    b.HasKey("Id")
                        .HasName("pk_operacao_cedente");

                    b.ToTable("operacao_cedente", (string)null);
                });

            modelBuilder.Entity(" Cliente.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodigoKeycloak")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codigo_keycloak");

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_exclusao");

                    b.Property<DateTime?>("DataInativacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_inativacao");

                    b.Property<DateTime?>("DataRegistro")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_registro");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("email");

                    b.Property<int>("IdConfiguracaoPerfil")
                        .HasColumnType("integer")
                        .HasColumnName("id_configuracao_perfil");

                    b.Property<int>("IdTipoUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_tipo_usuario");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nome");

                    b.Property<int>("Situacao")
                        .HasColumnType("integer")
                        .HasColumnName("situacao");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity(" Cliente.Domain.Entities.UsuarioEmpresa", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataAlteracao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_alteracao");

                    b.Property<DateTime?>("DataRegistro")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_registro");

                    b.Property<int>("IdEmpresa")
                        .HasColumnType("integer")
                        .HasColumnName("id_empresa");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id")
                        .HasName("pk_usuario_empresa");

                    b.ToTable("usuario_empresa", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
